### PR TITLE
Fix conditional for subcheck perfdata

### LINKED ISSUE #68: [Bug]: Perfdata inconsistency
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

0.2.0

### Describe the bug

The perfdata output is inconsistent: 

```
go run main.go alert -T 2 --name foo
[UNKNOWN] - 0 Alerts: 0 Firing - 0 Pending - 0 Inactive

go run main.go alert -T 1 --name foo --name NodeHasMemoryPressure
[OK] - 1 Alerts: 0 Firing - 0 Pending - 1 Inactive
\_ [OK] [NodeHasMemoryPressure] is inactive
|total=1 firing=0 pending=0 inactive=1
```

When there are no alerts found, there is no output. 

### How to recreate the bug?

_No response_

### LINKED ISSUE #83: [Bug]: Panic when passing multiple alert names
### Please try to fill out as much of the information below as you can. Thank you!

- [x] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

v0.3.0

### Describe the bug

Panic when passing multiple alert names:

```bash
go run main.go alert --name foo  --name bar
[UNKNOWN] - Golang encountered a panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
github.com/NETWAYS/go-check.CatchPanic()
	/home/mopolka/github/go/pkg/mod/github.com/!n!e!t!w!a!y!s/go-check@v0.6.2/exit.go:81 +0x75
panic({0xa375a0?, 0xc0001566f0?})
	/usr/local/go/src/runtime/panic.go:792 +0x132
github.com/NETWAYS/check_prometheus/cmd.init.func1(0xc000236000?, {0xa77a27?, 0x4?, 0xa779db?})
	/home/mopolka/github/go/src/github.com/NETWAYS/check_prometheus/cmd/alert.go:184 +0xdef
github.com/spf13/cobra.(*Command).execute(0xf927c0, {0xc000200420, 0x6, 0x6})
	/home/mopolka/github/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa7b
github.com/spf13/cobra.(*Command).ExecuteC(0xf93000)
	/home/mopolka/github/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x40c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mopolka/github/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/NETWAYS/check_prometheus/cmd.Execute({0xc000246000?, 0xc000002380?})
	/home/mopolka/github/go/src/github.com/NETWAYS/check_prometheus/cmd/root.go:27 +0x7d
main.main()
	/home/mopolka/github/go/src/github.com/NETWAYS/check_prometheus/main.go:18 +0x18

```

### How to recreate the bug?

```
cd testdata
docker compose up
```

```
go run main.go alert --name foo  --name bar
```

### PR DESCRIPTION
**Pull request by martialblog**
Rework alert output to be more consistent

 - Fixes panic when passing multiple alert names
 - More consistent perfdata output

Fixes #83 

Fixes #68

### CODE REVIEW

File: cmd/alert.go [hunk 1]
```diff
@@ -173,7 +173,7 @@ inactive = 0`,
 		}
 
 		counterAlert := counterFiring + counterPending + counterInactive
-		if len(cliAlertConfig.AlertName) > 1 || counterAlert > 1 {
```
Comment (martialblog) [inline cmd/alert.go:176]: No that's not it. But it's the condition being wrong, since it does not account for when there are no alerts being returned.

**Review by RincewindsHat — APPROVED** [review]
looks about right :-)

File: cmd/alert.go (hunk 1 above)
Comment (martialblog) [reply cmd/alert.go:176]: I reworked the alert.go a bit. Now it's a bit clearer
